export const GET_PRODUCTS_REQUEST = "shop/GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "shop/GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "shop/GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_REQUEST = "shop/GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "shop/GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "shop/GET_PRODUCT_FAILURE";

export const FILTER_PRODUCTS = "shop/FILTER_PRODUCTS";